### ISSUE TITLE
Unable to select spec talents, only class

### ISSUE THREAD

**Issue by DimitrisLK** [Breeni/BtWLoadouts#11]
Hello there!

As the title suggests, I downloaded the addon and, while trying to create some talents sets, I noticed that I could only select my class talents and there was no option to switch to the spec talents. 
For reference, I tried this on all Mage specs while a friend gave it a try on his Rogue. 

Is this the intended behavior?

Thanks in advance!

**Comment by Breeni** [comment]
You can drag the frame horizontally to see spec talents. I understand this is not the most intuitive system
