### ISSUE TITLE
Unable to Activate a Talent page after importing

### ISSUE THREAD

**Issue by DimitrisLK** [Breeni/BtWLoadouts#13]
Hello there and a happy New Year <3

I've encountered an interesting bug with the export/import feature of the addon. I've been trying to utilize the full power the addon provides so I've been making more and more talent pages to cover all those niche situations, which led me to creating copies of talent builds since most of the time I change one or two talents. 

So, I was exporting and then importing a talent page to create a copy of it and realized that the `Activate` button was getting disabled.
![Screenshot_2](https://user-images.githubusercontent.com/32920285/210161865-debbf04c-4a01-40b1-af3a-8bbd803648f6.png)
 
A workaround I found for that was, instead of just making the talent page from scratch every time, to create a `Loadout` for every talent page and activate that. Which, technically, solves the problem since I would have to create a loadout anyway to utilize the Condition sets. 

My first question would be if this is intended behavior and my second question/feature request is if it's possible to have an easier way of duplicating stuff without going through the constant `Export/Import` procedure all the time. 

Thank you for your time!

**Comment by Breeni** [comment]
I've fixed the issue with imported talent sets not being activatable with the latest version (v1.9.2). I'll look into adding a duplicate set feature in the future. Please let me know if you have any more issues.
