### ISSUE TITLE
Feature request: view both class and spec talent trees in the Talents tab

### ISSUE THREAD

**Issue by alexandre-mckinnon** [Breeni/BtWLoadouts#14]
Maybe I'm missing something, but in the BtWLoadouts interface, for talent, I only see the class tree and not the spec tree.

There is already a scrollbar going down, the two trees might be stacked on top of each other.

Top of the scroll page:
![image](https://user-images.githubusercontent.com/16991071/210625962-7dc04f9a-6bc2-4309-89f0-28c4893b044d.png)

Bottom of the scroll page
![image](https://user-images.githubusercontent.com/16991071/210625907-105a7e00-9eb9-4f65-8633-ccf248d77e32.png)

It's only the class tree.

**Comment by Breeni** [comment]
You can drag the talent tree horizontally to see the other tree
