### ISSUE TITLE
Feature Request: Action bars with certain button character only buttons 

### ISSUE THREAD

**Issue by kingreboot** [Breeni/BtWLoadouts#23]
Basically I use a trinket on my warrior that is saved to my action bar, but if I play another warrior and want to use that same profile, then an option to select a certain spell or button location to be locked to a certain character so my alt that does not have that trinket does not get it. Could also work for spells that are race based to only show up if your that race. Just a idea that can be expanded on

**Comment by Breeni** [comment]
I'm inclined to not allow that level of control per action button. However this can be solved another way, currently for racials its possible to add a second action bar set to a loadout that has a race restriction which can be set via the settings menu to the right of the name input. This doesnt solve per character trinkets though, I normally use a macro like "/use [mod:shift] 14; 13" but something more generic might be better.

**Comment by kingreboot** [comment]
an easier option I thought about was a filter similar to create character macros, but an option to exclude spells and trinkets that's not on the character.

**Comment by kingreboot** [comment]
the use mod shit macro is only good if I had a on use trinket on each alt that I use the same bar set up

**Comment by Breeni** [comment]
> an easier option I thought about was a filter similar to create character macros, but an option to exclude spells and trinkets that's not on the character.

This is actually how it works for spells already because you cant pick up a spell if its not known so I had to make sure the addon could test its availability. That wasnt necessary for items since it can pick up any item, even if you cant put them on the bars. A simple fix would be to check item count when deciding if a slot is valid. The only issue then is equipped items vs items in bags.

**Comment by kingreboot** [comment]
could you check both bag and equipped for bars? and on a low tech leveling, could you check level so alts can't get it on the bar while under the level of the trinket

**Comment by Breeni** [comment]
> could you check both bag and equipped for bars?

Yes that's possible. This is probably the simplest and best solution, effectively ignoring anything that is not currently available. This will be next on my list once the current beta build is fully released.

**Comment by kingreboot** [comment]
thanks

**Comment by kingreboot** [comment]
Still having issues

**Comment by kingreboot** [comment]
not sure if level matters, but the example I have is a level 61 warrior alt, trying to use a Loadout that includes a talent build and an action bar that includes the trinket puzzle box that I use on my main warrior

**Comment by Breeni** [comment]
In the action bar tab does it show the item with a red outline on the alt? It should show Item unavailable in the tooltip if there is none in your bags/equipped. Could you also check the addons version please? (it shows up in the log /btwloadouts log when you activate a loadout)

**Comment by kingreboot** [comment]
Actually it works. For some reason I thought I was on the most current build. seems to be fine and thanks for the fix
