### ISSUE TITLE
Bug - Loadouts not activating properly.

### ISSUE THREAD

**Issue by Jokinen86** [Breeni/BtWLoadouts#26]
Having issues with loadouts using talents and action bars. The talents don't load into my default raid loadout like it did before (basically importing over it) and it doesn't load in the different abilities to the action bar when activating a different loadout. Here are the two LUA errors I got:

> 1x BtWLoadouts/Equipment.lua:2142: ERROR
> [string "=[C]"]: in function `error'
> [string "@BtWLoadouts/Equipment.lua"]:2142: in function <BtWLoadouts/Equipment.lua:2116>
> [string "@BtWLoadouts/Equipment.lua"]:1301: in function <BtWLoadouts/Equipment.lua:1267>
> [string "@BtWLoadouts/Equipment.lua"]:1846: in function `OnButtonClick'
> [string "@BtWLoadouts/BtWLoadouts.lua"]:1653: in function `OnButtonClick'
> [string "*BtWLoadouts.xml:544_OnClick"]:1: in function <[string "*BtWLoadouts.xml:544_OnClick"]:1>
> 
> Locals:
> (*temporary) = "ERROR"

---

> 1x BtWLoadouts/BtWLoadouts.lua:1640: attempt to index field '?' (a nil value)
> [string "@BtWLoadouts/BtWLoadouts.lua"]:1640: in function `Update'
> [string "@BtWLoadouts/BtWLoadouts.lua"]:1777: in function <BtWLoadouts/BtWLoadouts.lua:1755>
> [string "=[C]"]: in function `SetShown'
> [string "@BtWLoadouts/Launcher.lua"]:17: in function `OnClick'
> [string "@Bartender4/libs/LibDBIcon-1.0-45/LibDBIcon-1.0.lua"]:144: in function <...dOns/Bartender4/libs/LibDBIcon-1.0/LibDBIcon-1.0.lua:142>
> 
> Locals:
> self = BtWLoadoutsFrame {
>  0 = <userdata>
>  OnEnter = <function> defined @BtWLoadouts/BtWLoadouts.lua:1555
>  SetEssenceSet = <function> defined @BtWLoadouts/BtWLoadouts.lua:1608
>  NPE = Frame {
>  }
>  OnDragStart = <function> defined @BtWLoadouts/BtWLoadouts.lua:1542
>  Sidebar = Frame {
>  }
>  OnShow = <function> defined @BtWLoadouts/BtWLoadouts.lua:1755
>  ActivateButton = Button {
>  }
>  OnDragStop = <function> defined @BtWLoadouts/BtWLoadouts.lua:1545
>  ExportButton = Button {
>  }
>  OnButtonClick = <function> defined @BtWLoadouts/BtWLoadouts.lua:1652
>  Conditions = Frame {
>  }
>  SetTitle = <function> defined @BtWLoadouts/BtWLoadouts.lua:1535
>  SetTitleOffsets = <function> defined @SharedXML/PortraitFrame.lua:54
>  SetPvPTalentSet = <function> defined @BtWLoadouts/BtWLoadouts.lua:1603
>  OnSidebarItemDoubleClick = <function> defined @BtWLoadouts/BtWLoadouts.lua:1658
>  SetNPEShown = <function> defined @BtWLoadouts/BtWLoadouts.lua:1791
>  OnMouseUp = <function> defined @BtWLoadouts/BtWLoadouts.lua:1548
>  OnTabChanged = <function> defined @BtWLoadouts/BtWLoadouts.lua:1573
>  TabFrames = <table> {
>  }
>  GetCurrentTab = <function> defined @BtWLoadouts/BtWLoadouts.lua:1634
>  Bg = BtWLoadoutsFrameBg {
>  }
>  SetConditionSet = <function> defined @BtWLoadouts/BtWLoadouts.lua:1621
>  SetTitleFormatted = <function> defined @SharedXML/PortraitFrame.lua:40
>  NineSlice = Frame {
>  }
>  OnLoad = <function> defined @BtWLoadouts/BtWLoadouts.lua:1515
>  OnResizeStop = <function> defined @BtWLoadouts/BtWLoadouts.lua:1563
>  ActionBars = Frame {
>  }
>  OnOptionsClick = <function> defined @BtWLoadouts/BtWLoadouts.lua:1726
>  Loadouts = BtWLoadoutsFrameLoadouts {
>  }
>  DeleteButton = Button {
>  }
>  Resize = Button {
>  }
>  Essences = Frame {
>  }
>  TabPool = <table> {
>  }
>  SetTitleMaxLinesAndHeight = <function> defined @SharedXML/PortraitFrame.lua:49
>  SetTitleColor = <function> defined @SharedXML/PortraitFrame.lua:32
>  SetSetByID = <function> defined @BtWLoadouts/BtWLoadouts.lua:1626
>  Tabs = <table> {
>  }
>  SetActionBarSet = <function> defined @BtWLoadouts/BtWLoadouts.lua:1617
>  TabSegments = <table> {
>  }
>  initialized = true
>  Export = Frame {
>  }
>  AddButton = Button {
>  }
>  OnSidebarItemClick = <function> defined @BtWLoadouts/BtWLoadouts.lua:1655
>  Equipment = Frame {
>  }
>  layoutType = "ButtonFrameTemplateNoPortraitMinimizable"
>  HelpTipBox = Frame {
>  }
>  Soulbinds = BtWLoadoutsFrameSoulbinds {
>  }
>  OnLeave = <function> defined @BtWLoadouts/BtWLoadouts.lua:1560
>  PvPTalents = BtWLoadoutsFramePvPTalents {
>  }
>  DFTalents = BtWLoadoutsFrameDFTalents {
>  }
>  Talents = BtWLoadoutsFrameTalents {
>  }
>  numTabs = 10
>  GetTitleText = <function> defined @SharedXML/PortraitFrame.lua:28
>  SetLoadout = <function> defined @BtWLoadouts/BtWLoadouts.lua:1593
>  SidebarInset = Frame {
>  }
>  OnHelpTipManuallyClosed = <function> defined @BtWLoadouts/BtWLoadouts.lua:1664
>  TitleContainer = Frame {
>  }
>  SetEquipmentSet = <function> defined @BtWLoadouts/BtWLoadouts.lua:1613
>  OnHide = <function> defined @BtWLoadouts/BtWLoadouts.lua:1779
>  OptionsButton = Button {
>  }
>  RefreshButton = Button {
>  }
>  Import = Frame {
>  }
>  OnSidebarItemDragStart = <function> defined @BtWLoadouts/BtWLoadouts.lua:1661
>  CloseButton = BtWLoadoutsFrameCloseButton {
>  }
>  BodyInset = Frame {
>  }
>  SetExport = <function> defined @BtWLoadouts/BtWLoadouts.lua:1734
>  Update = <function> defined @BtWLoadouts/BtWLoadouts.lua:1638
>  TopTileStreaks = BtWLoadoutsFrameTopTileStreaks {
>  }
>  selectedTab = 0
>  SetTalentSet = <function> defined @BtWLoadouts/BtWLoadouts.lua:1598
> }
> selectedTab = 0
> (*temporary) = nil
> (*temporary) = 0
> (*temporary) = nil
> (*temporary) = nil
> (*

**Comment by howlenoates** [comment]
I dont know if this is the same error but with the new patch and new talents on my shaman and death knight I had to remake my talent loadouts (that were saved in the addon not on the blizzard ui) for my loadouts to run properly. Even though the talent page in the addon updated, I think it was still treating it as old

**Comment by Breeni** [comment]
I've pushed an update (v1.13.2) with a fix, it may not solve everything, please let me know if you're still having issues.
