### ISSUE TITLE
Talent area gap

### ISSUE THREAD

**Issue by DimitrisLK** [Breeni/BtWLoadouts#27]
Hello there!

Just mentioning a random thing I noticed about the talent page.  As shown on the screenshot below, if you resize the addon window, the container for the talents doesn't get resized and the highlighted area doesn't get filled with talents. 
![image](https://user-images.githubusercontent.com/32920285/229208283-a813b41a-fe89-4c8a-8f8a-78a9ded464a8.png)

**Comment by DimitrisLK** [comment]
This was fixed in a previous update but appears to be broken again. Can only see scroll down to a certain level now. 
![image](https://user-images.githubusercontent.com/32920285/235839395-ba2d508f-6176-48be-b77d-e5d79dd10209.png)
![image](https://user-images.githubusercontent.com/32920285/235839314-94dbe200-136f-40b5-b7b8-aa024b55a482.png)

**Comment by Breeni** [comment]
This issue should hopefully be solved with the latest version (v1.14.2), please let me know if it persists.
