### ISSUE TITLE
Action bar profiles do not update toys and items not currently in inventory

### ISSUE THREAD

**Issue by TieJu** [Breeni/BtWLoadouts#29]
Currently it is no longer possible to set toys to action bar slots with the profiles. It seems toys are classified as items and there are none in the inventory, and so the application to the bars will ignore it. The same logic prevents setting updating bar slots with items currently unavailable.
I have a baseline layout with potions and temporary consumables, like healthstones, that are not always available by all characters. With the recent update, this is broken and represents a big reduction in functionality of this addon.
There is also the behavior on slots that are ignored because of this, they are not updated at all, this is confusing and first lead me to be live there was a script error that prevented bar slot updates at all, may be a better behavior in this case is to clear out the slot.
A good solution would be a option to control, what to do in case of missing items.

**Comment by Breeni** [comment]
The change was done to better handle multiple action bars sets with different trinkets or similar. For the time being I can update it to only ignore missing eqiuppable items. Would this solve your issues?

**Comment by TieJu** [comment]
Yes that would be much better.

**Comment by Breeni** [comment]
I have pushed a new version (v1.13.5) with this change, please let me know if you have any other issues.
