### ISSUE TITLE
LUA errors after patch 10.1

### ISSUE THREAD

**Issue by Odysseas68** [Breeni/BtWLoadouts#31]
After the patch 10.1 i got LUA errors. Using 1.14.1 version:

1x BtWLoadouts/PvPTalents.lua:104: attempt to compare nil with number
[string "@BtWLoadouts/PvPTalents.lua"]:104: in function `isActive'
[string "@BtWLoadouts/Loadouts.lua"]:356: in function <BtWLoadouts/Loadouts.lua:341>
[string "@BtWLoadouts/Loadouts.lua"]:371: in function <BtWLoadouts/Loadouts.lua:365>
[string "@BtWLoadouts/Loadouts.lua"]:378: in function <BtWLoadouts/Loadouts.lua:377>
[string "@BtWLoadouts/Loadouts.lua"]:438: in function `GetActiveProfiles'
[string "@BtWLoadouts/Events.lua"]:567: in function `EQUIPMENT_SETS_CHANGED'
[string "@BtWLoadouts/Events.lua"]:365: in function `?'
[string "@BtWLoadouts/Events.lua"]:19: in function <BtWLoadouts/Events.lua:18>

Locals:
set = <table> {
 talents = <table> {
 }
}
playerLevel = 70
talents = <table> {
}
slots = <table> {
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 158 = true
 3506 = true
 1213 = true
}
(for control) = 158
talentID = 158
(*temporary) = nil
(*temporary) = nil
(*temporary) = 158
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to compare nil with number"
GetPvpTalentUnlockLevel = <function> defined =[C]:-1
GetPvpTalentSlotInfo = <function> defined =[C]:-1

**Comment by Breeni** [comment]
I've uploaded a new version (v1.14.2) that should solve this issue, please let me know if it persists.
