### ISSUE TITLE
Lua error while selected a Mythic+ Affix in Condition

### ISSUE THREAD

**Issue by TaikooS** [Breeni/BtWLoadouts#37]
Yet the condition is still functional, so I guess it's just a UI error.

42x BtWLoadouts/Instances.lua:2673: attempt to index local 'b' (a nil value)
[string "@BtWLoadouts/Instances.lua"]:2673: in function `CompareAffixMasks'
[string "@BtWLoadouts/Conditions.lua"]:1100: in function `Update'
[string "@BtWLoadouts/Conditions.lua"]:1431: in function `Update'
[string "@BtWLoadouts/BtWLoadouts.lua"]:1704: in function `Update'
[string "@BtWLoadouts/Conditions.lua"]:1052: in function `func'
[string "@SharedXML/UIDropDownMenu.lua"]:1008: in function `UIDropDownMenuButton_OnClick'
[string "*UIDropDownMenuTemplates.xml:131_OnClick"]:1: in function <[string "*UIDropDownMenuTemplates.xml:131_OnClick"]:1>

Locals:
a = <table> {
 1 = 1024
}
b = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = 1024
(*temporary) = nil
(*temporary) = "attempt to index local 'b' (a nil value)"

**Comment by Breeni** [comment]
I'm a few months late but this should be fixed with the latest version (v1.52.2) please let me know if it persists.
