### ISSUE TITLE
Demon Hunter: Duplicate talent trees

### ISSUE THREAD

**Issue by mattlinsky** [Breeni/BtWLoadouts#41]
btwloadouts is showing duplicates of my WoW create talent trees

![image](https://github.com/Breeni/BtWLoadouts/assets/33098627/ca812135-cc84-4a6a-898c-324afc2f1a35)
![image](https://github.com/Breeni/BtWLoadouts/assets/33098627/71343293-86fa-434c-a564-f56410a54654)

**Comment by Breeni** [comment]
Sorry for the very late response. Are you still having this issue?
