### ISSUE TITLE
Since the last update on 25/01 the Equipment tab is broken

### ISSUE THREAD

**Issue by akaRaven** [Breeni/BtWLoadouts#42]
1. It no longer displays in a list of class/role/spec, just all listed under Other.
2. t now also displays your loadouts from your character AND a copied version in the addon.
3. When you click on one of the loadouts it just deletes it.

![image](https://github.com/Breeni/BtWLoadouts/assets/4547308/ecc79321-bb55-4e20-aa41-e666ba3c3a76)

When you reload the equipment lists do come back, so it's not a permanent deletion, but it does mean you cannot currently go in and edit the lists from the addon or even see what they are.

And when you try to set the equipment in the Loadouts tab you just get a list of both loadouts under Other.

![image](https://github.com/Breeni/BtWLoadouts/assets/4547308/4d697457-cc09-4572-afa8-ee69421ace82)

**Comment by Breeni** [comment]
In the latest release (v1.16.0) I've implemented a fix for equipment sets not showing the correct class. For handling role/spec it'll be based on selected restrictions, please let me know if its still not showing correct with the restrictions set.
