### ISSUE TITLE
Disable updating action bars of different specs or add confirmation popup

### ISSUE THREAD

**Issue by guicaulada** [Breeni/BtWLoadouts#44]
When you are in a certain specialization you can't update talents for other specialization, which makes sense, but a mistake I have been making often is updating the action bars from other specializations while on a different spec, causing me to erase all the action bars from the other spec and having to redo them, same thing sometimes happens with Equipment, would be cool if when you have a certain Loadout equipped if you try to update the Equipment or Action Bars from other specs or loadouts it at least warned you about it, or in the case of Action Bars if they were disabled like the Talents, I'm not sure if this is possible, I might give it a try and make a PR if you approve of the idea but don't have time.

**Comment by homezonebenny** [comment]
I absolutely **AGREE** on that!
It only should be **possible** to **see** and **load** and **CHANGE** profiles which are connected to the current class / specc.
*At least* it would be great to add a **LOCK** symbol on **right top** near to toolbar / x (close) symbol which hides all profiles which aren't for the **current class / specc.**

Maybe your feature request is somehow connected to mine too?
https://github.com/Breeni/BtWLoadouts/issues/48

**Comment by Breeni** [comment]
I've released a new version (v1.16.0) that now blocks updating action bar sets based on selected restrictions including race and class. Please let me know if you have any more issues.
