### ISSUE TITLE
Loadouts not changing equipment in 10.2.6 patch

### ISSUE THREAD

**Issue by phem0r** [Breeni/BtWLoadouts#45]
Activate a loadout - Action bars and Talents are changed accordingly but Equipment is not.

Recreated my wow saved equipment's and produced a new loadout in the addon, equipment still not loaded.

Happening since WoW 10.2.6 release

**Comment by Breeni** [comment]
I've uploaded a new version (v1.15.8) that should solve this issue, please let me know if it persists.

**Comment by phem0r** [comment]
Fixed, ty!
