### ISSUE TITLE
[Bug Fix/Enhancement] Talents

### ISSUE THREAD

**Issue by rhodan412** [Breeni/BtWLoadouts#5]
Am using just SexyMap and BtWLoadouts add-ons to test the functionality

Currently the talent load-outs only save the class talents and not the specialization talents.  I'm not sure if this is a bug with the release of the new DF talent system, but otherwise would be great to see it also save the spec tree.

**Comment by Breeni** [comment]
Is it not saving the spec talents or not letting you drag the talent screen sideways to show them?

**Comment by rhodan412** [comment]
Got it.  Didn't realize that the window for the talents was able to be dragged.  All is good.  Thank you.
