### ISSUE TITLE
Conditions creates lua error

### ISSUE THREAD

**Issue by Coccyx69** [Breeni/BtWLoadouts#52]
Settingg conditions raid, then picking aberrus

 Date: 2024-05-03 15:29:58
ID: 3
Error occured in: Global
Count: 1
Message: Interface/AddOns/BtWLoadouts/Conditions.lua line 768:
   bad argument #1 to 'ipairs' (table expected, got nil)
Debug:
   [string "=(tail call)"]: ?
   [string "=[C]"]: ?
   [string "=[C]"]: ipairs()
   [string "@Interface/AddOns/BtWLoadouts/Conditions.lua"]:768: func()
   [string "@Interface/SharedXML/UIDropDownMenu.lua"]:1019: UIDropDownMenuButton_OnClick()
   [string "*UIDropDownMenuTemplates.xml:134_OnClick"]:1:
      [string "*UIDropDownMenuTemplates.xml:134_OnClick"]:1
Locals:
(*temporary) = "LeftButton"
(*temporary) = false
(*temporary) = <function> defined =[C]:-1

AddOns:
  KalielsTracker, v6.5.1
  Swatter, v9.1.BETA.5.13 (OneMawTime)
  AddonFactory, v10.2.011
  AdiBags, vv1.10.26
  AdiBagsDragonflight, vv2.9.4
  AllTheThings, vDF-3.11.0
  Altoholic, v10.2.012
  AstralKeys, v4.03
  Auctionator, v10.2.37
  Auctioneer, v9.1.BETA.5.13 (OneMawTime)
  AuctioneerStatsOverTime, v9.1.BETA.5.13 (OneMawTime)
  AuctioneerUtilDealFinder, v9.1.BETA.5.13 (OneMawTime)
  AuctioneerUtilValuer, v9.1.BETA.5.13 (OneMawTime)
  BagBrother, v
  Bartender4, v4.14.16
  BattlePetBreedID, vv1.27.0
  BigWigs, vv328.1
  BtWLoadouts, vv1.16.0
  BtWQuests, v2.37.0
  BtWQuestsDragonflight, v8.0
  CamelSpotter, v1.7.16
  CharacterNotes, v10.2.0
  CursorTrail, v10.2.6.2
  DataStore, v2024.01.31
  DataStoreAchievements, v2024.01.31
  DataStoreAgenda, v2024.01.31
  DataStoreAuctions, v2024.01.31
  DataStoreCharacters, v2024.01.31
  DataStoreContainers, v2024.01.31
  DataStoreCrafts, v2024.01.31
  DataStoreCurrencies, v2024.01.31
  DataStoreGarrisons, v2024.01.31
  DataStoreInventory, v2024.01.31
  DataStoreMails, v2024.01.31
  DataStorePets, v2024.01.31
  DataStoreQuests, v2024.01.31
  DataStoreReputations, v2024.01.31
  DataStoreSpells, v2024.01.31
  DataStoreStats, v2024.01.31
  DataStoreTalents, v2024.01.31
  DBMCore, v10.2.37
  DBMStatusBarTimers, v10.2.37
  DBMVPVEM, v4a10f12
  DejaCharacterStats, vR100200r1
  Details, v#Details.20240503.12699.156
  DetailsCompare2, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  EasyFrames, v
  Enchantrix, v9.1.BETA.5.13 (OneMawTime)
  GSE, v3.1.68
  GSELDB, v3.1.68
  GSEUtils, v3.1.68
  GTFO, v5.7.1
  HandyNotes, vv1.6.19
  HandyNotesBattleForAzerothTreasures, vv31
  HandyNotesDragonflight, v46
  HandyNotesDragonflightTreasures, vv55
  HandyNotesMythicPlus, vV100105-0
  HealBotData, v
  HealBotOptions, v
  HealerStatWeights, v1.0.4
  Healium, v
  HeroCache, v10.2.6.03
  HeroDBC, v10.2.6.02
  HeroLib, v10.2.6.03
  HeroRotation, v10.2.6.17
  HeroRotationDemonHunter, v
  Informant, v9.1.BETA.5.13 (OneMawTime)
  InstanceAchievementTracker, v4.41.0
  KeystoneLoot, v1.7.0
  LagBar, v6.9
  NovaInstanceTracker, v1.55
  NPCScan, v9.0.1.3
  OmniCC, v10.2.6
  OmniCD, v10.2.7.2787
  OribosExchange, v1.1.20240503
  Pawn, v2.9.0
  PlayerRep, v6.2.02
  PointBlankSniper, v5.36
  Postal, vv4.1.3
  PremadeGroupsFilter, v5.4.0
  QuestCompletist, v109.46
  RaiderIO, v10.2.6 (v202405030600)
  Rarity, v1.0 (r730-release)
  RarityOptions, v
  Rematch, v5.1.4
  Scrap, v10.2.8
  SexyMap, vv10.2.7
  SilverDragon, vv2024.2
  SilverDragonOverlay, vv2024.2
  SilverDragonRangeExtender, vv2024.2
  Simulationcraft, v10.2.6-03
  SlideBar, v9.1.BETA.5.13 (OneMawTime)
  Stubby, v9.1.BETA.5.13 (OneMawTime)
  tdBattlePetScript, vv1.10.1
  TidyPlates, v6.21.7
  TidyPlatesGraphite, v
  TidyPlatesGrey, v
  TidyPlatesNeon, v
  TidyPlatesQuatre, v
  TidyPlatesHub, v
  TidyPlatesWidgets, v
  TomTom, vv3.6.1-release
  TradeSkillMaster, vv4.13.25
  TradeSkillMasterAppHelper, vv4.13.1
  UltraSquirt, v0.9.8
  WeakAuras, v5.12.9
  WeakAurasArchive, v5.12.9
  WowUp, v1.0.7
  wowupdataaddon, v1.0.7
  BlizRuntimeLib v10.2.6.54499(US) <enUS>
  (ck=c54)

**Comment by Breeni** [comment]
I've pushed a new version (v1.17.0) that should fix this error, please let me know if you have any more issues.
