### ISSUE TITLE
Feature Request: Group Conditions by Instance

### ISSUE THREAD

**Issue by Ansixd** [Breeni/BtWLoadouts#53]
Allow grouping of conditions by instance as a filter for example

 Dungeon
 -Brackenhide 
--Afflicted 
--Incorporeal
-Neltharus

 Raid
-Vault of the Incarnates
--Eranog
--Council
-Aberrus 
--Kazzara

and so on.

**Comment by Breeni** [comment]
I've released a new version that supports this, please let me know if you have any issues.
