### ISSUE TITLE
[Enhancement] Action Bars section

### ISSUE THREAD

**Issue by rhodan412** [Breeni/BtWLoadouts#6]
Similar to how the talents sort by class and specialization, could you implement functionality for Action Bars section?

I.E. Under Loadouts tab: When I choose "Protection - Open World" for TALENTS a menu comes up that breaks down by class and specialization, but when I chose Action Bars, a menu doesn't display that breaks down by class/spec and instead everything is sorted under "Other" (see attached pictures)
<img width="903" alt="btwloadout01" src="https://user-images.githubusercontent.com/84867920/198848828-7237fa1e-7
<img width="789" alt="btwloadout02" src="https://user-images.githubusercontent.com/84867920/198848856-3ebb4310-5feb-4d6d-934e-111cf7161cc3.png">
acd-4767-8e74-dd26bd8f26bd.png">

**Comment by rhodan412** [comment]
<img width="903" alt="btwloadout01" src="https://user-images.githubusercontent.com/84867920/198848871-4fa9822a-efe4-41ba-8248-7ce277a6f8fc.png">

**Comment by Breeni** [comment]
The dropdown menus are based on the filters selected within each tab. If you add class filters from the filter dropdown menu above the side bar for the action bars tab and set class restrictions for the different action bars sets from the cogwheel from the right of the name editbox you should get the same display as talents.

**Comment by rhodan412** [comment]
I see now how the menu system is configured.  Thank you for your quick response.  Sorry I didn't respond earlier.
