### ISSUE TITLE
[Feature Request] Talent Import

### ISSUE THREAD

**Issue by Konungrr** [Breeni/BtWLoadouts#7]
Would love to have an option to import talent build codes directly into the addon rather than having to import into the BlizzUI Talent frame, Create new set in addon, Update, Delete BlizzUI build.

Also, update the Action Bars to include the 3 new action bars. At least it looks to me that there are 3 new action bars, I only remember 10 bars in ElvUI before this patch, now there's 1-10, 13,14,15.

**Comment by Breeni** [comment]
Sorry for the delayed response. Although not exactly what you asked for, the addon now supports using Blizzard talent loadouts directly with the latest beta build (v1.10.0-beta). Once this feature is stable I'll begin working on direct importing without needing the Blizzard loadouts at all.

The extra action bars are also supported.

**Comment by Breeni** [comment]
We now support importing Blizzard loadouts strings directly into the Import tab.
